var fs=require('fs'),lines=[]; 
function w(f,a){fs.writeFileSync('photo-sorter/'+f,a.join('\n'),'utf8');console.log(f+' ok '+a.join('\n').length);} 
var db=[]; 
db.push("const DB_NAME='photo-sorter-v1',DB_VERSION=1,STORE_META='meta',STORE_THUMB='thumbs';\"); 
db.push("let _db=null;\"); 
db.push("function openDB(){if(_db)return Promise.resolve(_db);\"); 
db.push("  return new Promise((res,rej)=>{\"); 
db.push("    const req=indexedDB.open(DB_NAME,DB_VERSION);\"); 
db.push("    req.onupgradeneeded=e=>{\"); 
db.push("      const db=e.target.result;\"); 
db.push("      if(!db.objectStoreNames.contains(STORE_META))db.createObjectStore(STORE_META);\"); 
db.push("      if(!db.objectStoreNames.contains(STORE_THUMB))db.createObjectStore(STORE_THUMB);\"); 
db.push("    };\"); 
db.push("    req.onsuccess=e=>{_db=e.target.result;res(_db);};\"); 
db.push("    req.onerror=()=>rej(req.error);\"); 
db.push("  });\"); 
db.push("}\"); 
db.push("function fileKey(f){return f.name+'|'+f.size+'|'+f.lastModified;}\"); 
db.push("async function getMeta(file){\"); 
db.push("  const db=await openDB(),key=fileKey(file);\"); 
db.push("  return new Promise(r=>{\"); 
db.push("    const req=db.transaction(STORE_META,'readonly').objectStore(STORE_META).get(key);\"); 
db.push("    req.onsuccess=()=>r(req.result||null);req.onerror=()=>r(null);\"); 
db.push("  });\"); 
db.push("}\"); 
db.push("async function setMeta(file,meta){\"); 
db.push("  const db=await openDB(),key=fileKey(file);\"); 
db.push("  return new Promise(r=>{\"); 
db.push("    const tx=db.transaction(STORE_META,'readwrite');\"); 
db.push("    tx.objectStore(STORE_META).put(meta,key);\"); 
db.push("    tx.oncomplete=r;tx.onerror=r;\"); 
db.push("  });\"); 
db.push("}\"); 
db.push("async function getThumb(file){\"); 
db.push("  const db=await openDB(),key=fileKey(file);\"); 
db.push("  return new Promise(r=>{\"); 
db.push("    const req=db.transaction(STORE_THUMB,'readonly').objectStore(STORE_THUMB).get(key);\"); 
db.push("    req.onsuccess=()=>r(req.result||null);req.onerror=()=>r(null);\"); 
db.push("  });\"); 
db.push("}\"); 
db.push("async function setThumb(file,blob){\"); 
db.push("  const db=await openDB(),key=fileKey(file);\"); 
db.push("  return new Promise(r=>{\"); 
db.push("    const tx=db.transaction(STORE_THUMB,'readwrite');\"); 
db.push("    tx.objectStore(STORE_THUMB).put(blob,key);\"); 
db.push("    tx.oncomplete=r;tx.onerror=r;\"); 
db.push("  });\"); 
db.push("}\"); 
w('db.js',db); 
